name: Github Actions Workflow
on:
  push:
    branches:
      - master
jobs:
  check-linting:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache_obj
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache_obj.outputs.cache-hit != 'true'
        run: npm install
      - name: Run linting test
        run: npm run lint
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        id: cache_obj
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache_obj.outputs.cache-hit != 'truue'
        run: npm install
      - name: Run tests
        id: testing_step
        run: npm test
      - name: Upload test report
        if: ${{failure() && steps.testing_step.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  build:
    needs: run-tests
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.js_file_name.outputs.js-file-name }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        id: cache_obj
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache_obj.outputs.cache-hit != 'true'
        run: npm install
      - name: Deploy
        run: |
          echo "Building..."
          npm run build
          echo "Build complete!"
      - name: Publish JS filename
        id: js_file_name
        run: find dist/assets/*.js -type f -execdir echo 'js-file-name={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Output file name
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Get Build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Show files
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  test-job:
    needs: [check-linting, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output title
        run: echo "There are failed jobs ${{ github.actor }}..."


